### ISSUE TITLE
Minimap2 in new parabricks version

### ISSUE THREAD

**Issue by xuxocast** [Sydney-Informatics-Hub/Parabricks-Genomics-nf#33]
### Description of feature

Dear Georgie,

The most recent version of Parabricks includes Minimap2, and I need to run simple Minimap jobs, but I am having trouble using Parabricks on Gadi. Rather than a request for a feature, could you kindly provide some instructions or recommendations on how to achieve this?

I was trying to understand the logic behind your pipeline, but I can't find where you're calling or defining the "singularity run..." instruction. This would be my first time trying to run GPU-accelerated analysis. Is there something I’m not understanding about using Parabricks?

Thank you so much for your kind assistance.
Jesús (BABS, UNSW)

**Comment by georgiesamaha** [comment]
Hi @xuxocast, we're planning on implementing minimap2 in this pipeline when we have some time. Can't say when that'll be though. 

I suspect whats getting in the way of your understanding here is that:

1. We've written the workflow in Nextflow which separates out configuration away from the commands being run. 
2. We've used singularity containers to run some processes/modules that are not available through Parabricks, but not any process requiring Parabricks itself as it is globally installed in `/apps` on Gadi

If we take the Parabricks fq2bam process for example:

* The command is in [`modules/pb_fq2bam.nf`](https://github.com/Sydney-Informatics-Hub/Parabricks-Genomics-nf/blob/main/modules/pb_fq2bam.nf) 
* Its execution within the workflow is in the [`main.nf`](https://github.com/Sydney-Informatics-Hub/Parabricks-Genomics-nf/blob/main/main.nf)
* Configuration settings for singularity is in the [`nextflow.config`](https://github.com/Sydney-Informatics-Hub/Parabricks-Genomics-nf/blob/main/nextflow.config) and [`config/gadi.config`](https://github.com/Sydney-Informatics-Hub/Parabricks-Genomics-nf/blob/main/config/gadi.config)

In [`modules/pb_fq2bam.nf`](https://github.com/Sydney-Informatics-Hub/Parabricks-Genomics-nf/blob/147e1ebc0718d3c4d311c702eaf7d613e0b9df44/modules/pb_fq2bam.nf#L4), we've used the Parabricks module installed into `/apps` on Gadi and as such we've run the pbrun command without any Singularity run wrapper, because the module is already loaded. 

In the [`gadi.config`](https://github.com/Sydney-Informatics-Hub/Parabricks-Genomics-nf/blob/147e1ebc0718d3c4d311c702eaf7d613e0b9df44/config/gadi.config#L77-L83), we've defined resources required for each process. Note that `pb_fq2bam` is running on the gpuvolta queue and we've allocated resources according to that queue. 

Relevant nextflow and gadi documentation is here: 

* https://opus.nci.org.au/display/DAE/Nextflow 
* https://www.nextflow.io/docs/latest/reference/process.html#module

Hope that helps
